"""Docker Compose for Deskmate: the generated compose.local.yaml, the folders and secret files the compose
files need before `up`, and running `docker compose` from the repo with its output streamed line by line.

compose.yaml is the same for everyone; deploy/net-<mode>.yaml adds the network; compose.local.yaml (this
module writes it, gitignored) adds one read-only bind per folder the hub may read, at the same path inside
the container as on this computer, so a path in a transcript is a path the hub can open.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import time
import urllib.error
import urllib.request
from pathlib import Path

from . import detect, settings, util

LOCAL_NAME = "compose.local.yaml"
_CURRENT: dict = {"proc": None, "cancelled": False}

# Folders that would hide part of the hub's own container if mounted over it.
_INSIDE_FORBIDDEN = ("/app", "/data", "/exchange", "/run", "/proc", "/sys", "/dev", "/opt/novnc")
_EXACT_FORBIDDEN = ("/", "/etc", "/usr", "/bin", "/sbin", "/lib", "/lib64", "/var", "/opt", "/boot", "/root")


def local_path() -> Path:
    return settings.repo_dir() / LOCAL_NAME


def collides(path: str) -> str:
    """Why a folder can't be mounted at its own path in the hub ('' when it can)."""
    p = os.path.normpath(path or "")
    if not p.startswith("/"):
        return "Use a full path, starting with /."
    if p in _EXACT_FORBIDDEN:
        return f"{p} is a system folder; pick the folder you work in."
    for f in _INSIDE_FORBIDDEN:
        if p == f or p.startswith(f + "/") or f.startswith(p.rstrip("/") + "/"):
            return f"{p} would cover {f} inside the hub's container; pick another folder."
    if ":" in p:
        return "Folder names with ':' can't be used (':' separates the folders)."
    if re.search(r"[\x00-\x1f\x7f]", p):
        return "That folder name has control characters."
    return ""


def _inside(path: str, roots) -> bool:
    return any(path == r or path.startswith(r.rstrip("/") + "/") for r in roots)


def mounts(values: dict) -> tuple:
    """([sources], [missing]): the identity binds for the hub. <config>/projects of each Claude Code
    folder (never the whole folder: it holds the login), each session root, and the docs folder when
    it is outside the roots. Nothing when the secretary is off. A folder inside another is left out."""
    vals = settings.normalize(values)
    if not util.is_on(vals.get("SECRETARY", "on")):
        return [], []
    wanted = [os.path.join(d, "projects") for d in util.split_list(vals.get("CLAUDE_CONFIG_DIRS", ""))]
    wanted += util.split_list(vals.get("SESSIONS_ROOTS", ""))
    docs = (vals.get("DOCS_DIR") or "").rstrip("/")
    if docs:
        wanted.append(docs)
    wanted = [os.path.normpath(w) for w in wanted if w and not collides(w)]
    out, missing = [], []
    for w in sorted(set(wanted), key=lambda s: (s.count("/"), s)):
        if _inside(w, out):
            continue
        if not os.path.isdir(w):
            missing.append(w)
            continue
        out.append(w)
    order = {w: i for i, w in enumerate(wanted)}
    return sorted(out, key=lambda s: order.get(s, 0)), missing


def _yaml_str(s: str) -> str:
    """A double-quoted YAML scalar; '$' doubled because Compose interpolates it."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "$$") + '"'


def render_local(values: dict) -> str:
    sources, missing = mounts(values)
    lines = [
        "# Generated by ./deskmate setup from .env. Don't edit it: change the settings, then run ./deskmate up.",
        "# Read-only views of this computer for the hub, at the same paths as here.",
    ]
    for m in missing:
        lines.append(f"# Left out, the folder doesn't exist: {m}")
    lines.append("services:")
    if not sources:
        lines.append("  hub: {}")
    else:
        lines += ["  hub:", "    volumes:"]
        for src in sources:
            q = _yaml_str(src)
            lines += ["      - type: bind", f"        source: {q}", f"        target: {q}",
                      "        read_only: true", "        bind:", "          create_host_path: false"]
    return "\n".join(lines) + "\n"


def write_local(values: dict) -> Path:
    path = local_path()
    util.write_private(path, render_local(values), 0o600)
    return path


def in_step(values: dict) -> bool:
    """compose.local.yaml says what .env says."""
    try:
        return local_path().read_text(encoding="utf-8") == render_local(values)
    except OSError:
        return False


def compose_file_line(values: dict) -> str:
    return "COMPOSE_FILE=" + settings.compose_file_value(values)


# ---------------------------------------------------------------- folders and secret files


def prepare(values: dict, emit=None) -> bool:
    """Create what compose mounts, as the user, before the first `up` (a missing bind source would
    otherwise be created by Docker as root): the data folder and its parts (0700), every secret file
    (0600, empty is fine), each Claude Code folder's projects/, and compose.local.yaml."""

    def say(level, text):
        if emit:
            emit({"phase": "Prepare folders", "level": level, "text": text})

    vals = settings.normalize(values)
    data = settings.data_dir(vals)
    for sub in ("", "hub", "exchange", "secrets", "bin"):
        util.private_dir(data / sub if sub else data)
    say("ok", f"Data folder {util.tilde(str(data))} (only you can open it)")
    sec = data / "secrets"
    for name in settings.SECRET_NAMES:
        f = sec / name
        if not f.exists():
            util.write_private(f, "", 0o600)
        elif f.stat().st_uid == os.getuid() and util.mode_of(f) != 0o600:
            os.chmod(str(f), 0o600)
    if not settings.read_secret("hub-token", vals):
        say("error", "The hub token is missing. Run ./deskmate setup again.")
        return False
    notify_file = vals.get("NOTIFY_URL_FILE") or str(sec / "notify-url")
    if not os.path.isfile(notify_file):
        if os.path.normpath(notify_file) == os.path.normpath(str(sec / "notify-url")):
            util.write_private(Path(notify_file), "", 0o600)
        else:
            say("error", f"The webhook file {util.tilde(notify_file)} is gone. Set a new URL in ./deskmate setup, "
                         "or point NOTIFY_URL_FILE at the file.")
            return False
    say("ok", "Secret files in place (0600)")
    if util.is_on(vals.get("SECRETARY", "on")):
        for d in util.split_list(vals.get("CLAUDE_CONFIG_DIRS", "")):
            proj = Path(d, "projects")
            if not proj.exists() and (Path(d).is_dir() or os.path.normpath(d) == detect.default_config_dir()):
                util.private_dir(proj)  # Claude Code makes it on its first session anyway
                say("info", f"Made {util.tilde(str(proj))}, so sessions show up as they start")
    write_local(vals)
    sources, missing = mounts(vals)
    for m in missing:
        say("warn", f"{util.tilde(m)} doesn't exist, so the hub can't read it. Fix it in ./deskmate setup.")
    say("ok", f"compose.local.yaml: {len(sources)} read-only folder{'s' if len(sources) != 1 else ''} for the hub")
    return True


# ---------------------------------------------------------------- running docker compose


def compose_env(values: dict | None = None) -> dict:
    """The environment for `docker compose`: .env wins over the shell, so a TZ or COMPOSE_FILE exported
    for something else can't change what runs."""
    env = dict(os.environ)
    file_values = settings.read_env()
    for k, v in file_values.items():
        env[k] = v
    if values:
        for k, v in settings.normalize(values).items():
            if k in settings.ENV_KEYS and isinstance(v, str):
                env[k] = v
    if "DESK_NETWORK" in env:
        env["COMPOSE_FILE"] = settings.compose_file_value(env)
    env["COMPOSE_PATH_SEPARATOR"] = ":"
    env.setdefault("BUILDKIT_PROGRESS", "plain")
    env["DOCKER_CLI_HINTS"] = "false"
    env.pop("COMPOSE_PROFILES", None)
    return env


def _docker_path() -> str:
    return detect.docker()["path"] or "docker"


def _level(line: str) -> str:
    low = line.lower()
    if re.search(r"\berror\b|failed to |cannot |can't |no such ", low):
        return "error"
    if re.search(r"\bwarn(ing)?\b", low):
        return "warn"
    return "info"


def run(args, emit=None, phase: str = "Docker", values: dict | None = None) -> int:
    """`docker compose <args>` in the repo; every output line goes to emit() (secrets scrubbed).
    Returns the exit code (130 when cancelled, 127 when Docker is missing)."""
    cmd = [_docker_path(), "compose", "--ansi", "never"] + [str(a) for a in args]
    secrets = settings.all_secret_values(values)
    try:
        proc = subprocess.Popen(cmd, cwd=str(settings.repo_dir()), env=compose_env(values), stdin=subprocess.DEVNULL,
                                stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, encoding="utf-8",
                                errors="replace", bufsize=1)
    except OSError as exc:
        if emit:
            emit({"phase": phase, "level": "error", "text": f"Couldn't run docker: {exc}"})
        return 127
    _CURRENT["proc"] = proc
    try:
        for raw in proc.stdout:
            line = util.scrub(raw.rstrip("\r\n"), secrets)
            if line.strip() and emit:
                emit({"phase": phase, "level": _level(line), "text": line})
        code = proc.wait()
    finally:
        _CURRENT["proc"] = None
        proc.stdout.close()
    if _CURRENT.get("cancelled"):
        return 130
    return code


def passthrough(args, values: dict | None = None) -> int:
    """`docker compose <args>` attached to this terminal (logs -f, ps), for the CLI."""
    cmd = [_docker_path(), "compose"] + [str(a) for a in args]
    try:
        return subprocess.call(cmd, cwd=str(settings.repo_dir()), env=compose_env(values))
    except KeyboardInterrupt:
        return 0
    except OSError as exc:
        print(f"Couldn't run docker: {exc}")
        return 127


def capture(args, timeout: float = 60.0, values: dict | None = None):
    """(code, stdout, stderr) of `docker compose <args>`."""
    return util.run([_docker_path(), "compose", "--ansi", "never"] + list(args), timeout=timeout,
                    env=compose_env(values), cwd=settings.repo_dir())


def cancel() -> None:
    """Stop the docker compose command that is running (the web wizard's Stop)."""
    _CURRENT["cancelled"] = True
    proc = _CURRENT.get("proc")
    if proc is not None and proc.poll() is None:
        try:
            proc.terminate()
        except OSError:
            pass


def reset_cancel() -> None:
    _CURRENT["cancelled"] = False


def ps(values: dict | None = None) -> list:
    """[{service, name, state, status, health}] of this project's containers."""
    code, out, _ = capture(["ps", "-a", "--format", "json"], timeout=30, values=values)
    if code != 0:
        return []
    items = []
    text = out.strip()
    if text.startswith("["):
        try:
            items = json.loads(text)
        except ValueError:
            items = []
    else:
        for line in text.splitlines():
            try:
                items.append(json.loads(line))
            except ValueError:
                continue
    return [{"service": o.get("Service", ""), "name": o.get("Name", ""), "state": o.get("State", ""),
             "status": o.get("Status", ""), "health": o.get("Health", "")} for o in items if isinstance(o, dict)]


# ---------------------------------------------------------------- talking to the hub


def http(port, path: str = "/", method: str = "GET", headers: dict | None = None, body: bytes | None = None,
         timeout: float = 5.0):
    """(status, headers, body) from the hub on 127.0.0.1; status 0 when nothing answers. Never raises."""
    req = urllib.request.Request(f"http://127.0.0.1:{port}{path}", data=body, method=method, headers=headers or {})
    opener = urllib.request.build_opener(urllib.request.ProxyHandler({}))  # never through a proxy
    try:
        with opener.open(req, timeout=timeout) as resp:
            return resp.status, dict(resp.headers), resp.read(200_000)
    except urllib.error.HTTPError as exc:
        try:
            data = exc.read(20_000)
        except Exception:  # noqa: BLE001
            data = b""
        return exc.code, dict(exc.headers or {}), data
    except Exception:  # noqa: BLE001 - refused, reset, timeout: nothing answered
        return 0, {}, b""


def wait_for_hub(port, timeout: float = 90.0, emit=None, phase: str = "Start Deskmate") -> bool:
    """Poll the hub's page until it answers (the containers take a few seconds to start)."""
    deadline = time.monotonic() + timeout
    told = False
    while time.monotonic() < deadline:
        if _CURRENT.get("cancelled"):
            return False
        status, _, _ = http(port, "/", timeout=3)
        if 200 <= status < 500:
            return True
        if not told and emit:
            emit({"phase": phase, "level": "info", "text": f"Waiting for the hub on 127.0.0.1:{port}…"})
            told = True
        time.sleep(1.0)
    return False


def signin_url(values: dict | None = None) -> str:
    port = (settings.normalize(values or {}).get("HUB_PORT") or settings.read_env().get("HUB_PORT") or "7800")
    token = settings.read_secret("hub-token", values)
    return f"http://127.0.0.1:{port}/login?t={token}" if token else ""
